<?php

namespace AppBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
	public function showAllSeries()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.categorie','desc')
            ->getQuery()
            ->getResult();
    }
}
