<?php

namespace AppBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{
	 public function getSerieByDate()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.dateProduction','desc')
            ->getQuery()
            ->getResult();
    }
     public function getSerieByType()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.categorie','desc')
            ->getQuery()
            ->getResult();
    }
}
